name: Run dev tests for server code

on:
  pull_request:
    branches:
      - dev
    paths:
      - aind-metadata-service-server/**

jobs:
  tests:
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    uses: AllenNeuralDynamics/.github/.github/workflows/test-ci.yml@main
    with:
      working-directory: aind-metadata-service-server
      python-version: ${{ matrix.python-version }}
